
import type { Equipment } from './types';

export const EQUIPMENT_LIST: Equipment[] = [
  { name: 'Continuous Hot Extraction Equipment' },
  { name: 'Percolator' },
  { name: 'Tincture Press' },
  { name: 'Grinding Mill' },
  { name: 'Disintegrator' },
  { name: 'Tablet Machine' },
  { name: 'Tablet Hardness Tester' },
  { name: 'Granulating Sieve Set' },
  { name: 'Tablet Counter Small Size' },
  { name: 'Friability Tester' },
  { name: 'Distillation Equipment for Distilled Water (Glass)' },
  { name: 'Disintegration Test Unit' },
  { name: 'Sintered glass filters for bacterial proof Filtration' },
  { name: 'Millipore filter (3 Grades) 2 each' },
  { name: 'Autoclave' },
  { name: 'Hot Air Sterilizer' },
  { name: 'Incubator' },
  { name: 'Tube Filling and Sealing Equipments' },
  { name: 'Prescription Balance/Dispensing Balance' },
  { name: 'Pill Tiles' },
  { name: 'Balance Torsion tupe with removable glass pan sensitivity, 30 mgm' },
  { name: 'Water Deionization Unit' },
  { name: 'Pressure Cookers' },
  { name: 'Aseptic Cabinet' },
  { name: 'Blender' },
  { name: 'Sieves Set (Pharmacopoeia Standard)' },
  { name: 'Laboratory Centrifuge' },
  { name: 'Ointment Slabs' },
  { name: 'Ointment Spatulas' },
  { name: 'Pestle and Mortar (Porcelain)' },
  { name: 'Pestle and Mortar (Glass)' },
  { name: 'Suppository Moulds of 3 size' },
  { name: 'Horn Spatulas' },
  { name: 'Refrigerator' },
  { name: 'Macerating Jar' },
  { name: 'Presses' },
  { name: 'Chopping board & Knife' },
  { name: 'Water bath Metal circular' },
  { name: 'Succession Machine (Automatic)' },
  { name: 'Potentizer (Automatic)' },
  { name: 'Evaporating dishes' },
  { name: 'Pycnometer' },
  { name: 'Storage Tank' },
  { name: 'Ointment Pots' },
  { name: 'Barometer' },
  { name: 'General Glassware' },
  { name: 'Chemical Appliances Laboratory Facilities' },
];
